<?php

/**
 * @file
 * Primary module hooks for BoxUK Patterns module.
 */

/**
 * Implements hook_entity_bundle_info_alter().
 */
function boxuk_patterns_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['article'])) {
    // phpcs:ignore Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing
    $bundles['node']['article']['class'] = \Drupal\boxuk_patterns\Entity\Node\BoxUkArticle::class;
  }
}

/**
 * Implements hook_theme().
 */
function boxuk_patterns_theme($existing, $type, $theme, $path): array {
  return [
    'node__article' => [
      'base hook' => 'node',
      'template' => 'node--article',
    ],
  ];
}

